config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  
  resource :dashboard, only: [:show]
  resources :lessons, only: [:index, :show, :references] do 
    member do 
      get 'references'
      get 'enrollment_list'
    end
    resources :enrollments, only: :create
    resources :word_expositions, only: [:show, :update]
    resources :scrambled_words, only: [:show, :update]
    resources :word_dictations, only: [:show, :update]
    resources :image_spellings, only: [:show, :update]
  end
  resources :words, only: [:show]
  namespace :teacher do
    resources :lessons, only: [:show, :new, :edit, :create, :update, :destroy] do 
      resources :words, only: [:new, :edit, :create, :update, :destroy]
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  has_many :words, -> { order('created_at ASC') }, dependent: :destroy 
  has_many :enrollments, dependent: :destroy
  has_many :scrambled_words, through: :enrollments
  has_many :word_expositions, through: :enrollments
  has_many :word_dictations, through: :enrollments
  has_many :image_spellings, through: :enrollments

  before_save :strip_whitespace
  
  validates :title, presence: true, length: { maximum: 55 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :subject, presence: true, length: { maximum: 55 }
  validates :difficulty, presence: true, numericality: { less_than_or_equal_to: 6 }

  def reset_activities
    word_expositions.update_all(completed: false)
    scrambled_words.update_all(completed: false)
    word_dictations.update_all(completed: false)
    image_spellings.update_all(completed: false)
  end

  def enrollment_for(student_user)
    return nil unless student_user
    enrollments.find_by(user: student_user)
  end

  private
    def strip_whitespace
      self.title = self.title.split.join(' ')
      self.description = self.description.split.join(' ')
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @lessons = Lesson.order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def references
    @lesson = Lesson.find(params[:id])
  end

  def enrollment_list
    @lesson = Lesson.find(params[:id])
  end

  helper_method :activities_completed?
  def activities_completed?(user)
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(user)
      current_enrollment.completed
    end
  end

  helper_method :expositions_complete?
  def expositions_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.expositions_completed
    end
  end

  helper_method :unscrambled_complete?
  def unscrambled_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.unscrambled_completed
    end
  end

  helper_method :dictation_complete?
  def dictation_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.dictation_completed
    end
  end

  helper_method :image_spellings_complete?
  def image_spellings_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.image_spelling_completed
    end
  end

  helper_method :enrolled_users
  def enrolled_users
    lesson = Lesson.find(params[:id])
    enrollments = lesson.enrollments.order('created_at ASC')
    enrolled_users = enrollments.map { |enrollment| enrollment.user }
  end
  
  #this helper method will be phased out
  # helper_method :completed_expo
  # def completed_expo
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_expositions = current_enrollment.word_expositions
  #     all_expositions.all? { |word_expo| word_expo.completed == true }
  #   end
  # end

  # #this helper method will be phased out
  # helper_method :completed_unscramble
  # def completed_unscramble
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_unscramble = current_enrollment.scrambled_words
  #     all_unscramble.all? { |scrambled| scrambled.completed == true }
  #   end
  # end

  # #this helper method will be phased out
  # helper_method :completed_dictations
  # def completed_dictations
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_dictations = current_enrollment.word_dictations
  #     all_dictations.all? { |dictation| dictation.completed == true }
  #   end
  # end

  # #this helper method will be phased out
  # helper_method :completed_spellings
  # def completed_spellings
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_spellings = current_enrollment.image_spellings
  #     all_spellings.all? { |spelling| spelling.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_scram
  # def completed_scram
  #   lesson = Lesson.find(params[:id])
  #   completed_scram = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_unscramble = current_enrollment.scrambled_words
  #     user if all_unscramble.all? { |scrambled| scrambled.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_expos
  # def completed_expos
  #   lesson = Lesson.find(params[:id])
  #   completed_expos = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_expos = current_enrollment.word_expositions
  #     user if all_expos.all? { |expos| expos.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_dicts
  # def completed_dicts
  #   lesson = Lesson.find(params[:id])
  #   completed_dic = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_dicts = current_enrollment.word_dictations
  #     user if all_dicts.all? { |dict| dict.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_spel
  # def completed_spel
  #   lesson = Lesson.find(params[:id])
  #   completed_sp = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_sp = current_enrollment.image_spellings
  #     user if all_sp.all? { |spell| spell.completed == true }
  #   end
  # end
end

app/controllers/teacher/lessons_controller.rb
class Teacher::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson, only: [:show, :edit, :update, :destroy]

  def show
    lesson
  end

  def new
    @lesson = Lesson.new
  end

  def edit
    lesson
  end

  def create
    @lesson = current_user.lessons.create(lesson_params)
    if @lesson.valid?
      flash[:notice] = "Lesson created!"
      redirect_to teacher_lesson_path(@lesson)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if lesson.update(lesson_params)
      flash[:notice] = "Lesson information updated!"
      redirect_to teacher_lesson_path(lesson)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    lesson.destroy
    flash[:notice] = "Lesson destroyed."
    redirect_to dashboard_path
  end
  
  private
    def require_authorized_for_current_lesson
      if lesson.user != current_user
        render text: "Unauthorized", status: :unauthorized
      end
    end

    def lesson
      @lesson ||= Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :description, :subject, :difficulty)
    end
end

app/controllers/teacher/words_controller.rb
class Teacher::WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson

  def new
    @word = Word.new
  end

  def edit
    @word = Word.find(params[:id])
  end

  def create
    @word = current_lesson.words.create(word_params)
    if @word.valid?
      current_lesson.reset_activities
      flash[:notice] = "Word successfully created!"
      redirect_to teacher_lesson_path(current_lesson)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @word = Word.find(params[:id])

    if @word.update(word_params)
      current_lesson.reset_activities
      flash[:notice] = "Word successfully updated!"
      redirect_to teacher_lesson_path(current_lesson)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    flash[:notice] = "Word deleted."
    redirect_to teacher_lesson_path(current_lesson)
  end

  private

    def require_authorized_for_current_lesson
      if current_lesson.user != current_user
        render text: 'Unauthorized', status: :unauthorized
      end
    end

    helper_method :current_lesson
    def current_lesson
      @current_lesson ||= Lesson.find(params[:lesson_id])
    end

    def word_params
      params.require(:word).permit(:term, :reference, :image, :sound)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/teacher/lessons_helper.rb
module Teacher::LessonsHelper
end

app/helpers/teacher/words_helper.rb
module Teacher::WordsHelper
end

app/views/teacher/lessons/edit.html.erb
<% content_for :title, "Edit Lesson" %>

<br>
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Lesson</h1>

  <br>

  <%= simple_form_for @lesson, url: teacher_lesson_path(@lesson), method: :patch do |f| %>
    <%= f.input :title %><br>
    <%= f.input :description %><br>
    <%= f.input :subject, :label => "Choose language", :collection => ['Spanish', 'English', 'French', 'German', 'Latin', 'Chinese', 'Russian'] %><br>
    <%= f.input :difficulty, :label => "Choose difficulty", :collection => [1,2,3,4,5,6] %><br><br>
    <%= f.submit "Update", class: 'btn btn-primary' %>
  <% end %>
  
  <br>

  <div class="text-right">
    <%= link_to 'Back to Lesson Admin', teacher_lesson_path(@lesson) %>
  </div>
  
</div>

<br class="clear">
<br>

app/views/teacher/lessons/new.html.erb
<% content_for :title, "New Lesson" %>

<br>
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>New Lesson</h1>

  <br>

  <%= simple_form_for @lesson, url: teacher_lessons_path do |f| %>
    <%= f.input :title %><br>
    <%= f.input :description %><br>
    <%= f.input :subject, :label => "Choose language", :collection => ['Spanish', 'English', 'French', 'German', 'Latin', 'Chinese', 'Russian'], :selected => "Spanish" %><br>
    <%= f.input :difficulty, :label => "Choose difficulty", :collection => [1,2,3,4,5,6], :selected => 1 %><br><br>
    <%= f.submit "Create Lesson", class: 'btn btn-primary' %>
  <% end %>
  
  <br> 

  <div class="text-right">
    <%= link_to 'Back to Lessons', lessons_path, class: 'btn btn-info' %>
  </div>
  
</div>

<br class="clear">
<br>

app/views/teacher/lessons/show.html.erb
<% content_for :title, @lesson.title + " (admin)" %>

<br>
<div class ="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= @lesson.title %></h1>
  <h2 class="text-center"><%= @lesson.subject %> <%= @lesson.difficulty %></h2>
  <br>
  <p class="text-center text-muted gen-text">(you created this lesson)</p>
  <br>
  <p class="text-center gen-text"><%= @lesson.description %></p>
  <br>
  <div class="text-center">
    <%= link_to 'Edit Lesson', edit_teacher_lesson_path(@lesson), class: 'btn btn-primary' %>
    <%= link_to 'Student View', lesson_path(@lesson), class: 'btn btn-warning' %>
    <%= link_to 'My Lessons', dashboard_path, class: 'btn btn-info' %>
  </div>
  
  <hr>
  
  <h3>This Lesson contains <%= @lesson.words.count %> words</h3>
  <br>
  <div class="text-center">
    <%= link_to 'Add a word', new_teacher_lesson_word_path(@lesson), class: 'btn btn-success btn-lg' %>
  </div>
  
  <br class="clear">
  <br>
  
  <% if @lesson.words.empty? %>
    <i>(this lesson doesn't have any vocabulary yet!)</i>
  <% end %>

  <ul>
    <% @lesson.words.each do |word| %>
      <li> 
        <%= image_tag word.image_url(:thumb) %> &nbsp
        
        <span class="gen-text"><%= word.term %></span> &nbsp

        <%= audio_tag word.sound, class: "lesson-audio-play" %>
        <button type="button" class="btn btn-default lesson-audio-button">
          <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
        </button> &nbsp
        
        <i>(<%= word.reference %>)</i> &nbsp

        <%= link_to 'Edit Word', edit_teacher_lesson_word_path(@lesson, word), class: 'btn btn-primary' %> &nbsp

        <%= link_to 'Delete Word', teacher_lesson_word_path(@lesson, word), 
            method: :delete,
            data: { confirm: 'This will permanently delete this word. Are you sure?' },
            class: 'btn btn-danger' %>
      </li>
      <br>
    <% end %>
  </ul>
</div>

<br class="clear">
<br>