config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  
  resource :dashboard, only: [:show]
  resources :lessons, only: [:index, :show, :references] do 
    member do 
      get 'references'
      get 'enrollment_list'
    end
    resources :enrollments, only: :create
    resources :word_expositions, only: [:show, :update]
    resources :scrambled_words, only: [:show, :update]
    resources :word_dictations, only: [:show, :update]
    resources :image_spellings, only: [:show, :update]
  end
  resources :words, only: [:show]
  namespace :teacher do
    resources :lessons, only: [:show, :new, :edit, :create, :update, :destroy] do 
      resources :words, only: [:new, :edit, :create, :update, :destroy]
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  has_many :words, -> { order('created_at ASC') }, dependent: :destroy 
  has_many :enrollments, dependent: :destroy
  has_many :scrambled_words, through: :enrollments
  has_many :word_expositions, through: :enrollments
  has_many :word_dictations, through: :enrollments
  has_many :image_spellings, through: :enrollments

  before_save :strip_whitespace
  
  validates :title, presence: true, length: { maximum: 55 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :subject, presence: true, length: { maximum: 55 }
  validates :difficulty, presence: true, numericality: { less_than_or_equal_to: 6 }

  def reset_activities
    word_expositions.update_all(completed: false)
    scrambled_words.update_all(completed: false)
    word_dictations.update_all(completed: false)
    image_spellings.update_all(completed: false)
  end

  def enrollment_for(student_user)
    return nil unless student_user
    enrollments.find_by(user: student_user)
  end

  private
    def strip_whitespace
      self.title = self.title.split.join(' ')
      self.description = self.description.split.join(' ')
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @lessons = Lesson.order('created_at DESC').paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def references
    @lesson = Lesson.find(params[:id])
  end

  def enrollment_list
    @lesson = Lesson.find(params[:id])
  end

  helper_method :activities_completed?
  def activities_completed?(user)
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(user)
      current_enrollment.completed
    end
  end

  helper_method :expositions_complete?
  def expositions_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.expositions_completed
    end
  end

  helper_method :unscrambled_complete?
  def unscrambled_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.unscrambled_completed
    end
  end

  helper_method :dictation_complete?
  def dictation_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.dictation_completed
    end
  end

  helper_method :image_spellings_complete?
  def image_spellings_complete?
    lesson ||= Lesson.find(params[:id])
    if current_enrollment = lesson.enrollment_for(current_user)
      current_enrollment.image_spelling_completed
    end
  end

  helper_method :enrolled_users
  def enrolled_users
    lesson = Lesson.find(params[:id])
    enrollments = lesson.enrollments.order('created_at ASC')
    enrolled_users = enrollments.map { |enrollment| enrollment.user }
  end
  
  #this helper method will be phased out
  # helper_method :completed_expo
  # def completed_expo
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_expositions = current_enrollment.word_expositions
  #     all_expositions.all? { |word_expo| word_expo.completed == true }
  #   end
  # end

  # #this helper method will be phased out
  # helper_method :completed_unscramble
  # def completed_unscramble
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_unscramble = current_enrollment.scrambled_words
  #     all_unscramble.all? { |scrambled| scrambled.completed == true }
  #   end
  # end

  # #this helper method will be phased out
  # helper_method :completed_dictations
  # def completed_dictations
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_dictations = current_enrollment.word_dictations
  #     all_dictations.all? { |dictation| dictation.completed == true }
  #   end
  # end

  # #this helper method will be phased out
  # helper_method :completed_spellings
  # def completed_spellings
  #   lesson = Lesson.find(params[:id])
  #   if current_enrollment = lesson.enrollment_for(current_user)
  #     all_spellings = current_enrollment.image_spellings
  #     all_spellings.all? { |spelling| spelling.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_scram
  # def completed_scram
  #   lesson = Lesson.find(params[:id])
  #   completed_scram = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_unscramble = current_enrollment.scrambled_words
  #     user if all_unscramble.all? { |scrambled| scrambled.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_expos
  # def completed_expos
  #   lesson = Lesson.find(params[:id])
  #   completed_expos = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_expos = current_enrollment.word_expositions
  #     user if all_expos.all? { |expos| expos.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_dicts
  # def completed_dicts
  #   lesson = Lesson.find(params[:id])
  #   completed_dic = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_dicts = current_enrollment.word_dictations
  #     user if all_dicts.all? { |dict| dict.completed == true }
  #   end
  # end

  # #for all users
  # helper_method :completed_spel
  # def completed_spel
  #   lesson = Lesson.find(params[:id])
  #   completed_sp = enrolled_users.map do |user|
  #     current_enrollment = lesson.enrollment_for(user)
  #     all_sp = current_enrollment.image_spellings
  #     user if all_sp.all? { |spell| spell.completed == true }
  #   end
  # end
end

app/controllers/teacher/lessons_controller.rb
class Teacher::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson, only: [:show, :edit, :update, :destroy]

  def show
    lesson
  end

  def new
    @lesson = Lesson.new
  end

  def edit
    lesson
  end

  def create
    @lesson = current_user.lessons.create(lesson_params)
    if @lesson.valid?
      flash[:notice] = "Lesson created!"
      redirect_to teacher_lesson_path(@lesson)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if lesson.update(lesson_params)
      flash[:notice] = "Lesson information updated!"
      redirect_to teacher_lesson_path(lesson)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    lesson.destroy
    flash[:notice] = "Lesson destroyed."
    redirect_to dashboard_path
  end
  
  private
    def require_authorized_for_current_lesson
      if lesson.user != current_user
        render text: "Unauthorized", status: :unauthorized
      end
    end

    def lesson
      @lesson ||= Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :description, :subject, :difficulty)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/teacher/lessons_helper.rb
module Teacher::LessonsHelper
end

app/views/lessons/enrollment_list.html.erb
<% content_for :title, @lesson.title + " (enrollments)" %>

<div class="col-xs-8 col-xs-offset-2 enroll-box">
  <h2 class="text-center"><%= @lesson.title %></h2>
  <h4 class="text-center">by <%= @lesson.user.username %> (<%= @lesson.subject %> <%= @lesson.difficulty %>)</h4>

  <h3>Enrolled users:</h3>

  <% if enrolled_users.count == 0 %>
    <p>There are no enrolled users in this lesson.</p>
  <% end %>

  <% enrolled_users.uniq.each do |user| %>
    <ul class="list-square">
      <li>
        <%= user.username %>
          <!-- Check for all activities completed -->
        <% if activities_completed?(user) %>
          <i class="fa fa-check-circle" id="check-completed-lesson"></i>
        <% end %>
      </li>    
    </ul>
  <% end %>

  <br>

  <div class="text-center">
    <%= link_to 'Back to Lesson', lesson_path(@lesson), class: "btn btn-primary"  %>
  </div>

  <br>

</div>

<div class="clear"></div>

<br>

app/views/lessons/index.html.erb
<% content_for :title, "Lessons" %>

<br>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">All Lessons</h1>
  <hr>
  <% @lessons.each do |lesson| %>
    <% unless lesson.words.empty? %>
      <h2><%= link_to lesson.title, lesson_path(lesson) %></h2>
      <span class="text-warning gen-text">by <%= lesson.user.username %> <br>
      <%= lesson.words.count %> words (<%= lesson.subject %> <%= lesson.difficulty %>)</span>
      <br>
      <span class="text-success gen-text"><%= lesson.description %></span><br>
      <%= link_to 'View Lesson', lesson_path(lesson), class: 'btn btn-primary view-button' %>
      <br><br>
    <% end %>
  <% end %>

  <br>
  <%= will_paginate @lessons, class: 'flickr_pagination' %>
  <br>

  <div class="text-center">
    <%= social_share_button_tag("Learn languages at Karooly!") %>
  </div>
</div>

<br class="clear">
<br>

app/views/lessons/references.html.erb
<% content_for :title, @lesson.title + " (references)" %>

<br>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= @lesson.title %></h1>
  <h4 class="text-center">by <%= @lesson.user.username %> (<%= @lesson.subject %> <%= @lesson.difficulty %>)</h4>
  <br>
  <p class="text-center gen-text"><%= @lesson.description %></p>
  <br>
  <p class="text-center gen-text"><%= @lesson.words.count %> words</p>
  
  <hr>

  <h2 class="text-center">References</h2>
  
  <br>

  <% if @lesson.words.empty? %>
    <i>(this lesson doesn't have any vocabulary yet!)</i>
  <% end %>
  
  <ul class="list-square">
    <% @lesson.words.each do |word| %>
      <li>
        <%= image_tag word.image_url(:thumb) %> &nbsp 
        <%= word.reference %>
      </li>
      <br>
    <% end %>
  </ul>

  <br>

  <div class="text-center">
    <%= link_to 'Back to Lesson', lesson_path(@lesson), class: "btn btn-primary"  %>
  </div>

  <br>
</div>

<div class="clear"></div>

<br>

app/views/lessons/show.html.erb
<% content_for :title, @lesson.title %>

<br>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= @lesson.title %></h1>
  <h4 class="text-center">by <%= @lesson.user.username %> (<%= @lesson.subject %> <%= @lesson.difficulty %>)</h4>
  <br>
  <p class="text-center gen-text"><%= @lesson.description %></p>
  <br>
  <p class="text-center gen-text"><%= @lesson.words.count %> words</p>
  
  <!-- hide user-enroll-info from printer view-->
  <div class="user-enroll-info">
    <div class="text-center">
      <% if current_user && current_user == @lesson.user %>
        <br>
        <%= link_to 'Lesson Admin', teacher_lesson_path(@lesson), class: 'btn btn-danger btn-large' %><br>
        <% if @lesson.words.empty? %>
          <br>
          <p>This lesson doesn't have any words. <%= link_to "Add", new_teacher_lesson_word_path(@lesson) %> your vocabulary so users can enroll.</p>
        <% end  %>
      <% end %>
        
      <% current_enrollment = @lesson.enrollment_for(current_user) %>
        
      <% if current_enrollment %>
        <br>
        <h2 class="label label-primary">You are enrolled!</h2>
      <% elsif current_user && !@lesson.words.empty? %>
        <br>
        <%= link_to 'Enroll', lesson_enrollments_path(@lesson), class: 'btn btn-primary', method: :post %>
      <% end %>

      <% if !current_user && !@lesson.words.empty? %>
        <br>
        <%= link_to 'Log in to enroll in this lesson', new_user_session_path, class: 'btn btn-primary' %>
      <% elsif @lesson.words.empty? %>
        <br>
        <p>(You will be able to enroll in this lesson once its creator uploads vocabulary.)</p>
      <% end %>
    </div>

    <% if current_enrollment %>
      <hr>
    <% end %>

    <!-- Display completed activities -->
    <% if current_enrollment && (expositions_complete? || unscrambled_complete? || dictation_complete? || image_spellings_complete?) %>
      <h3>Completed Activities</h3>

      <p><i>(Try them again for practice!)</i></p>

      <% if expositions_complete? %>
        <%= link_to "Exposition", lesson_word_exposition_path(@lesson, @lesson.words.first), class: 'label label-info' %>
      <% end %>

      <% if unscrambled_complete? %>
        <%= link_to "Unscramble", lesson_scrambled_word_path(@lesson, current_enrollment.first_scrambled_word.word), class: 'label label-info' %>
      <% end %>

      <% if dictation_complete? %>
        <%= link_to "Dictation", lesson_word_dictation_path(@lesson, current_enrollment.first_word_dictation.word), class: 'label label-info' %>
      <% end %>

      <% if image_spellings_complete? %>
        <%= link_to "Spelling", lesson_image_spelling_path(@lesson, current_enrollment.first_image_spelling.word), class: 'label label-info' %>
      <% end %>
    <% end %>

    <!-- Display incomplete activities -->
    <% if current_enrollment && (!expositions_complete? || !unscrambled_complete? || !dictation_complete? || !image_spellings_complete?) %>
      <h3>Activities To Be Completed</h3>
      <% if !expositions_complete? %>
        <%= link_to "Exposition", lesson_word_exposition_path(@lesson, @lesson.words.first), class: 'label label-warning' %> 
      <% end %>

      <% if !unscrambled_complete? %>
        <%= link_to "Unscramble", lesson_scrambled_word_path(@lesson, current_enrollment.first_scrambled_word.word), class: 'label label-warning' %>
      <% end %>

      <% if !dictation_complete? %>
        <%= link_to "Dictation", lesson_word_dictation_path(@lesson, current_enrollment.first_word_dictation.word), class: 'label label-warning' %>
      <% end %>

      <% if !image_spellings_complete? %>
        <%= link_to "Spelling", lesson_image_spelling_path(@lesson, current_enrollment.first_image_spelling.word), class: 'label label-warning' %> 
      <% end %>

    <% end %>

  </div> <!-- end page info -->
  
  <hr>

  <h2 class="text-center">VOCABULARY</h2>
  
  <br>

  <% if @lesson.words.empty? %>
    <i>(this lesson doesn't have any vocabulary yet!)</i>
  <% end %>
  
  <ul class="list-square">
    <% @lesson.words.each do |word| %>
      <li>
        <%= image_tag word.image_url(:thumb) if word.image? %> &nbsp
        <%= link_to word.term, word_path(word), class: "gen-text unselectable" %>
      </li>
      <br>
    <% end %>
  </ul>

  <br>

  <div class="text-center social-icons">
    <%= social_share_button_tag("\"#{@lesson.title}\" (#{@lesson.subject} #{@lesson.difficulty}) at Karooly!") %>
  </div>

  <br>
  
  <div class="print-icon text-right">
    <mark><%= link_to 'References', references_lesson_path %></mark>
    
    <br><br>

    <span class="bg-success"><%= link_to 'View enrollments', enrollment_list_lesson_path %></span>

    <br><br>

    <%= link_to @lesson, :onclick => 'window.print();return false;' do %>
      <i class="fa fa-print fa-2x" aria-hidden="true"></i>
    <% end %>
  </div>

</div>

<br class="clear">
<br>