config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  
  resource :dashboard, only: [:show]
  resources :lessons, only: [:index, :show, :references] do 
    member do 
      get 'references'
      get 'enrollment_list'
    end
    resources :enrollments, only: :create
    resources :word_expositions, only: [:show, :update]
    resources :scrambled_words, only: [:show, :update]
    resources :word_dictations, only: [:show, :update]
    resources :image_spellings, only: [:show, :update]
  end
  resources :words, only: [:show]
  namespace :teacher do
    resources :lessons, only: [:show, :new, :edit, :create, :update, :destroy] do 
      resources :words, only: [:new, :edit, :create, :update, :destroy]
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user_lessons = current_user.lessons.order('created_at ASC')
    @user_enrolled_lessons = current_user.enrolled_lessons.order('created_at ASC')
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.erb
<% content_for :title, "Dashboard (#{current_user.username})"  %>

<br>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center text-success"><%= current_user.username %> (dashboard)</h1>
  <br>

  <h2>My Lessons</h2>
  <% if @user_lessons.empty? %>
    <p><i>You haven't created any lessons. 
      <!-- temporary disable
      <%= link_to 'Create', new_teacher_lesson_path %> one.</i> -->
    </p>
  <% end %>

  <ul>
    <% @user_lessons.each do |lesson| %>
      <li class="gen-text"><%= link_to lesson.title, teacher_lesson_path(lesson) %> (<%= lesson.subject %> <%= lesson.difficulty %>, <%= lesson.words.count %> words): <%= lesson.description %>
        <br>
        <%= link_to 'Lesson Admin', teacher_lesson_path(lesson), class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Delete Lesson', teacher_lesson_path(lesson), 
            method: :delete,
            data: { confirm: 'ATTENTION: You are about to permanently delete this lesson and all of its words. Are you sure?' },
            class: 'btn btn-danger btn-sm' %>      
      </li>
      <br>
    <% end %>
  </ul>

  <hr>

  <h2>Lessons You Are Enrolled In</h2>
  <ul>
    <% @user_enrolled_lessons.each do |lesson| %>
    <li class="gen-text">
      <%= link_to lesson.title, lesson_path(lesson) %> (<%= lesson.subject %> <%= lesson.difficulty %>, by <%= lesson.user.username %>): <%= lesson.description %>
    </li>
    <br>
  <% end %>
  </ul>
</div>

<br class="clear">
<br>