config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'about', to: 'static_pages#about'
  
  resource :dashboard, only: [:show]
  resources :lessons, only: [:index, :show, :references] do 
    member do 
      get 'references'
      get 'enrollment_list'
    end
    resources :enrollments, only: :create
    resources :word_expositions, only: [:show, :update]
    resources :scrambled_words, only: [:show, :update]
    resources :word_dictations, only: [:show, :update]
    resources :image_spellings, only: [:show, :update]
  end
  resources :words, only: [:show]
  namespace :teacher do
    resources :lessons, only: [:show, :new, :edit, :create, :update, :destroy] do 
      resources :words, only: [:new, :edit, :create, :update, :destroy]
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :lesson
  has_many :word_expositions, dependent: :destroy
  has_many :scrambled_words, dependent: :destroy
  has_many :word_dictations, dependent: :destroy
  has_many :image_spellings, dependent: :destroy

  before_save :strip_whitespace

  mount_uploader :image, ImageUploader
  mount_uploader :sound, SoundUploader

  validates :term, presence: true, length: { maximum: 55 }
  validates :reference, presence: true, length: { maximum: 55 }
  validates :image, presence: true
  validates :sound, presence: true, file_size: { less_than_or_equal_to: 100.kilobytes }

  def previous
    Word.where(["id < ? AND lesson_id = ?", id, lesson_id]).last
  end

  def next
    Word.where(["id > ? AND lesson_id = ?", id, lesson_id]).first
  end

  private
    def strip_whitespace
      self.term = self.term.split.join(' ')
      self.reference = self.reference.split.join(' ')
    end
end

app/controllers/teacher/lessons_controller.rb
class Teacher::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson, only: [:show, :edit, :update, :destroy]

  def show
    lesson
  end

  def new
    @lesson = Lesson.new
  end

  def edit
    lesson
  end

  def create
    @lesson = current_user.lessons.create(lesson_params)
    if @lesson.valid?
      flash[:notice] = "Lesson created!"
      redirect_to teacher_lesson_path(@lesson)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if lesson.update(lesson_params)
      flash[:notice] = "Lesson information updated!"
      redirect_to teacher_lesson_path(lesson)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    lesson.destroy
    flash[:notice] = "Lesson destroyed."
    redirect_to dashboard_path
  end
  
  private
    def require_authorized_for_current_lesson
      if lesson.user != current_user
        render text: "Unauthorized", status: :unauthorized
      end
    end

    def lesson
      @lesson ||= Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :description, :subject, :difficulty)
    end
end

app/controllers/teacher/words_controller.rb
class Teacher::WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_lesson

  def new
    @word = Word.new
  end

  def edit
    @word = Word.find(params[:id])
  end

  def create
    @word = current_lesson.words.create(word_params)
    if @word.valid?
      current_lesson.reset_activities
      flash[:notice] = "Word successfully created!"
      redirect_to teacher_lesson_path(current_lesson)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @word = Word.find(params[:id])

    if @word.update(word_params)
      current_lesson.reset_activities
      flash[:notice] = "Word successfully updated!"
      redirect_to teacher_lesson_path(current_lesson)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    flash[:notice] = "Word deleted."
    redirect_to teacher_lesson_path(current_lesson)
  end

  private

    def require_authorized_for_current_lesson
      if current_lesson.user != current_user
        render text: 'Unauthorized', status: :unauthorized
      end
    end

    helper_method :current_lesson
    def current_lesson
      @current_lesson ||= Lesson.find(params[:lesson_id])
    end

    def word_params
      params.require(:word).permit(:term, :reference, :image, :sound)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  before_action :authenticate_user!, only: [:show]

  def show
  end

  private

    helper_method :current_word
    def current_word
      @current_word ||= Word.find(params[:id])
    end
end

app/helpers/teacher/lessons_helper.rb
module Teacher::LessonsHelper
end

app/helpers/teacher/words_helper.rb
module Teacher::WordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/teacher/words/edit.html.erb
<% content_for :title, "Edit Word" %>

<br>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Word</h1>
  <%= simple_form_for @word, url: teacher_lesson_word_path(current_lesson, @word), method: :patch do |f| %>
    <%= f.input :term %><br>
    <%= f.input :reference %><br>

    <p class="text-warning">Please make sure that you either hold the <%= link_to 'usage rights', 'https://support.google.com/websearch/answer/29508?hl=en', target: '_blank' %> of any files you upload to Karooly, or that they are <mark>labelled for reuse with modification</mark> if you gathered them from the Internet (e.g. Google Images) <i class="fa fa-smile-o" aria-hidden="true"></i></p><br>
    
    <%= f.input :image, input_html: { accept: "image/gif, image/jpeg, image/jpg, image/png" } %><br>
    <%= f.input :sound, input_html: { accept: "audio/mp3, audio/wma, audio/wav, audio/ra, audio/ram, audio/rm, audio/mid, audio/ogg, audio/aac, audio/aif, audio/iff, audio/m3u, audio/m4a, audio/mpa" } %>
    <br>
    <%= f.submit "Update", class: 'btn btn-primary btn-large' %>
  <% end %>

  <br><br>

  <div class="text-right">
    <%= link_to 'Back to Lesson Admin', teacher_lesson_path(current_lesson) %>
  </div>
  
</div>

<div class="clear"></div>

<br>

app/views/teacher/words/new.html.erb
<% content_for :title, "New Word" %>

<br>

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a Word</h1>
  <%= simple_form_for @word, url: teacher_lesson_words_path(current_lesson) do |f| %>
    <%= f.input :term %><br>
    <%= f.input :reference %><br>

    <p class="text-warning">Please make sure that you either hold the <%= link_to 'usage rights', 'https://support.google.com/websearch/answer/29508?hl=en', target: '_blank' %> of any files you upload to Karooly, or that they are <mark>labelled for reuse with modification</mark> if you gathered them from the Internet (e.g. Google Images) <i class="fa fa-smile-o" aria-hidden="true"></i></p><br>

    <%= f.input :image, input_html: { accept: "image/gif, image/jpeg, image/jpg, image/png" } %><br>
    <%= f.input :sound, input_html: { accept: "audio/mp3, audio/wma, audio/wav, audio/ra, audio/ram, audio/rm, audio/mid, audio/ogg, audio/aac, audio/aif, audio/iff, audio/m3u, audio/m4a, audio/mpa" } %>
    <br>
    <%= f.submit "Add word", class: 'btn btn-primary btn-large' %>
  <% end %>
  
  <br><br>

  <div class="text-right">
    <%= link_to 'Back to Lesson Admin', teacher_lesson_path(current_lesson) %>
  </div>
  
</div>

<div class="clear"></div>

<br>